<?php $this->headTitle('Album Page'); ?>

<a href="<?=$this->url('album.add')?>">Add Album</a>

<table class="table">
	<tr>
		<th>Title</th>
		<th>Artist</th>
		<th>Options</th>
	</tr>
	<?php if (! $this->albums) : ?>
		<tr>
			<td colspan="3" align="center">No album found.</td>
		</tr>
	<?php else:
		foreach ($this->albums as $album) : ?>
		<tr>
			<td><?php echo $this->escapeHtml($album->getTitle()) ?></td>
			<td><?php echo $this->escapeHtml($album->getArtist()) ?></td>
			<td>
                <a href="<?=$this->url('album.edit', ['id' => $album->getId()->toString()])?>">Edit</a> &nbsp;|&nbsp; <a href="<?=$this->url('album.delete', ['id' => $album->getId()->toString()])?>">Delete</a>
			</td>
		</tr>
	<?php endforeach;
	endif; ?>
</table>